terminal:
  colorScheme:
    name: deep
    foreground: '#cdcdcd'
    background: '#000000'
    cursor: '#d0d0d0'
    colors:
      - '#000000'
      - '#d11600'
      - '#37c32c'
      - '#e3c421'
      - '#5c6bfd'
      - '#dd5be5'
      - '#6eb4f2'
      - '#e0e0e0'
      - '#535353'
      - '#f4152c'
      - '#01ea10'
      - '#ffee1d'
      - '#8cb0f8'
      - '#e056f5'
      - '#67ecff'
      - '#f4f4f4'
  font: Delugia Nerd Font Regular
  fontSize: 16
  environment: {}
  ligatures: false
  rightClick: paste
  copyOnSelect: true
  autoOpen: true
  bell: audible
  frontend: hterm
  profile: default-(wsl-/-default-distro)
hotkeys:
  profile: {}
  shell: {}
  clear:
    - - Ctrl-L
  split-right:
    - - Ctrl-D
  copy:
    - - Ctrl-C
  paste:
    - - Ctrl-V
  new-tab:
    - - Ctrl-T
  search:
    - - Ctrl-F
serial: {}
ssh: {}
appearance:
  tabsLocation: top
  vibrancyType: fluent
  frame: thin
  dock: top
  theme: Standard
  dockFill: 0.6
enableWelcomeTab: false
pluginBlacklist: []
